import { test, expect } from '@playwright/test';

test('UI Integration - Dynamic Stock Analysis', async ({ page }) => {
  // 1. Open Dashboard
  await page.goto('http://localhost:3000/dashboard');
  
  // Dashboard loaded once "View plan" is available

  // 2. Click "View plan" on the first signal card
  const viewPlanButton = page.locator('text="View plan"').first();
  await viewPlanButton.waitFor({ state: 'visible', timeout: 5000 });
  await viewPlanButton.click();
  
  // 3. Verify navigation to Stock Analysis page
  await page.waitForURL(/\/dashboard\/analysis\/.+/);
  
  // 4. Verify Strategy Card and Trade Plan components exist
  await expect(page.locator('text=Matched Strategy').first()).toBeVisible();
  await expect(page.locator('text="Quantitative Trigger Rules"').first()).toBeVisible();
  await expect(page.locator('text="Trade Plan"').first()).toBeVisible();
  await expect(page.locator('text="Save to Journal"').first()).toBeVisible();

  // Handle the alert modal generated by the UI before clicking Save
  page.on('dialog', dialog => dialog.accept());

  // 5. Click "Save to Journal"
  const saveButton = page.locator('text="Save to Journal"');
  await saveButton.click();
  
  // 6. Verify navigation to Journal page
  await page.waitForURL(/\/dashboard\/journal/);
  await expect(page.locator('h1').first()).toContainText('Trade Journal');
});
